
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavHeader from "@/components/global/navigation/NavHeader";
import Footer from "@/components/global/Footer";

const outfit = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={outfit.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                  <NavHeader />
        
        {children}

                          <Footer className="w-full z-50" position="static" opacity={0} />
                          <Footer className="w-full" position="fixed" opacity={1} />
                  
      </body>
    </html>
  );
}
